#!/bin/bash

user=$USER;
#hostname=$HOSTNAME;
host=hostnamectl;
data=$(date +%d/%m/%y);
hora=$(date +%H:%M:%S);
ip=$(curl ifconfig.me);

echo $hostname

$host > /home/$USER/Variados/SMI/log/computador.txt;
#echo $hostname, > /home/$USER/Variados/SMI/log/acesso.txt;
cat /etc/hostname > /home/$USER/Variados/SMI/log/acesso.txt;
echo ,  >> /home/$USER/Variados/SMI/log/acesso.txt;log;
echo $user, >> /home/$USER/Variados/SMI/log/acesso.txt;
echo $data, >> /home/$USER/Variados/SMI/log/acesso.txt;
echo $hora, >> /home/$USER/Variados/SMI/log/acesso.txt;
echo $ip, >> /home/$USER/Variados/SMI/log/acesso.txt;


echo $data >> /home/$USER/Variados/SMI/log/log.txt;
echo $hora >> /home/$USER/Variados/SMI/log/log.txt;

echo ======================= >> /home/$USER/Variados/SMI/log/log.txt;

