#!/bin/bash
  
usuario=$USER;

#echo $usuario;
#update-rc.d nome-do-script defaults
#update-rc.d nome-do-script remove


apt moo
sh /home/raphael/Variados/SMI/shell/dados
sleep 40
php /home/raphael/Variados/SMI/php/exec.php
~                                             